title: Observing the User Experience
description: By Elizabeth Goodman and Mike Kuniavsky
theme: just-the-docs

url: https://mikekuniavsky.github.io/OUE3e

aux_links: # remove if you don't want this link to appear on your pages
##  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
